# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_auto_20160810_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='caller_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller_type_object_fk', to='calls.Object'),
        ),
        migrations.AlterField(
            model_name='call',
            name='receiver_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_type_object_fk', to='calls.Object'),
        ),
    ]
