# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20160810_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='caller_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller_type_object_fk', to='calls.Object', to_field='object_id'),
        ),
        migrations.AlterField(
            model_name='call',
            name='receiver_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_type_object_fk', to='calls.Object', to_field='object_id'),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_id',
            field=models.IntegerField(unique=True),
        ),
    ]
