# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_auto_20160811_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Call',
        ),
    ]
