# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_auto_20160811_2133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Call',
            new_name='Caller',
        ),
    ]
