# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0012_auto_20160811_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caller',
            new_name='CallLog',
        ),
    ]
