# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0035_auto_20160811_1409'),
        ('visitors', '0009_auto_20160811_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryAnalysisReferenceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.LaboratoryAnalysis')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.Species')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryAnalysisUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='laboratoryanalysisreferencevalue',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.LaboratoryAnalysisUnit'),
        ),
    ]
