# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_laboratorypanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryanalysisreferencevalue',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.LaboratoryPanel'),
        ),
    ]
