# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_auto_20160811_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorypanel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
