# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0036_laboratoryanalysispanel'),
        ('laboratory', '0008_auto_20160811_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='newthing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='laboratorydevicetype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
