# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_auto_20160811_1101'),
        ('laboratory', '0010_auto_20160811_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryPanelReferenceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Analysis', models.CharField(max_length=50)),
                ('min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.LaboratoryPanel')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.Species')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.LaboratoryAnalysisUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
