# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_laboratorypanelreferencevalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorypanelreferencevalue',
            old_name='Analysis',
            new_name='analysis',
        ),
        migrations.RenameField(
            model_name='laboratorypanelreferencevalue',
            old_name='Panel',
            new_name='panel',
        ),
    ]
