# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0014_auto_20160811_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaboratoryPanel',
            new_name='Panel',
        ),
    ]
