# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0016_auto_20160812_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Panel')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.LaboratoryAnalysisUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='laboratoryanalysisreferencevalue',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='laboratoryanalysisreferencevalue',
            name='species',
        ),
        migrations.RemoveField(
            model_name='laboratoryanalysisreferencevalue',
            name='unit',
        ),
        migrations.DeleteModel(
            name='LaboratoryAnalysisReferenceValue',
        ),
    ]
