# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_auto_20160812_2233'),
        ('laboratory', '0019_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='panelreference',
            name='created',
        ),
        migrations.RemoveField(
            model_name='panelreference',
            name='id',
        ),
        migrations.RemoveField(
            model_name='panelreference',
            name='max',
        ),
        migrations.RemoveField(
            model_name='panelreference',
            name='min',
        ),
        migrations.RemoveField(
            model_name='panelreference',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='panelreference',
            name='species',
        ),
        migrations.CreateModel(
            name='AnalysisReference',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laboratory.Reference')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Analysis')),
            ],
            options={
                'abstract': False,
            },
            bases=('laboratory.reference',),
        ),
        migrations.AddField(
            model_name='reference',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.Species'),
        ),
        migrations.AddField(
            model_name='panelreference',
            name='reference_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laboratory.Reference'),
            preserve_default=False,
        ),
    ]
