# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_auto_20160812_2233'),
        ('laboratory', '0020_auto_20160813_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='species',
        ),
        migrations.RenameField(
            model_name='analysisreference',
            old_name='panel',
            new_name='analysis',
        ),
        migrations.RemoveField(
            model_name='analysisreference',
            name='reference_ptr',
        ),
        migrations.RemoveField(
            model_name='panelreference',
            name='reference_ptr',
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='species',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='visitors.Species'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelreference',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='panelreference',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelreference',
            name='max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelreference',
            name='min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelreference',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='panelreference',
            name='species',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='visitors.Species'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
