# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0025_auto_20160807_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
    ]
