# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0027_auto_20160808_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalnotes',
            options={'verbose_name_plural': 'clinical notes'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'status'},
        ),
    ]
