# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 22:45
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0021_auto_20160820_1220'),
        ('consultations', '0030_auto_20160811_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='patient',
        ),
        migrations.AddField(
            model_name='consultation',
            name='patients',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='client', chained_model_field='client', to='visitors.Patient'),
        ),
    ]
