# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0034_auto_20160821_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
