# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0035_auto_20160821_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalnotes',
            options={'verbose_name': 'Clinical Notes', 'verbose_name_plural': 'Clinical Notes'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Consultation', 'verbose_name_plural': 'Consultations'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diangosis', 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='treatmentplan',
            options={'verbose_name': 'Treatment Plan', 'verbose_name_plural': 'Treatment Plans'},
        ),
        migrations.AlterField(
            model_name='clinicalnotes',
            name='clinical_notes',
            field=models.CharField(max_length=1000, verbose_name='Clinical Notes'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='attending_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vet/Nurse'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.Client', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consult Finish'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last updated by'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patients',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='client', chained_model_field='client', to='visitors.Patient', verbose_name='Animals'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='start',
            field=models.DateTimeField(verbose_name='Consult Start'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.CharField(max_length=1000, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation',
            field=models.CharField(max_length=1000, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='treatment_plan',
            field=models.CharField(max_length=1000, verbose_name='Treatment Plan'),
        ),
    ]
