# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='costprice',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='margin_percent',
            new_name='markup',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_with_vat',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wholesale_price',
        ),
        migrations.AddField(
            model_name='item',
            name='saleprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.ItemType'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.ItemCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='costpricevatrate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='costpricevatrate', to='items.VatRate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='salepricevatrate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='salepricevatrate', to='items.VatRate'),
            preserve_default=False,
        ),
    ]
