# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_auto_20160807_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='typex',
        ),
        migrations.DeleteModel(
            name='Itemtype',
        ),
    ]
