# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_item_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'item categories'},
        ),
    ]
