# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_auto_20160809_1617'),
        ('items', '0030_auto_20160809_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryAnalysisReferenceValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Laboratory',
            new_name='LaboratoryAnalysis',
        ),
        migrations.AddField(
            model_name='laboratoryanalysisreferencevalues',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.LaboratoryAnalysis'),
        ),
        migrations.AddField(
            model_name='laboratoryanalysisreferencevalues',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.Species'),
        ),
    ]
