# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0031_auto_20160809_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_price_vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costpricevatrate', to='items.VatRate'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_price_vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salepricevatrate', to='items.VatRate'),
        ),
    ]
