# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0033_auto_20160811_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaboratoryAnalysisReferenceValues',
            new_name='LaboratoryAnalysisReferenceValue',
        ),
        migrations.AlterModelOptions(
            name='laboratoryanalysis',
            options={'verbose_name_plural': 'laboratory analyses'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name_plural': 'supplies'},
        ),
    ]
