# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_auto_20160811_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoryanalysisreferencevalue',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='laboratoryanalysisreferencevalue',
            name='species',
        ),
        migrations.DeleteModel(
            name='LaboratoryAnalysisReferenceValue',
        ),
    ]
