# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_auto_20160811_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryAnalysisPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.SampleType')),
            ],
            options={
                'verbose_name_plural': 'laboratory analysis panels',
            },
        ),
    ]
