# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0036_laboratoryanalysispanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('procedure', 'Procedure'), ('medicine', 'Medicine'), ('supply', 'Supply'), ('food', 'Food'), ('analysis', 'Analysis'), ('panel', 'Panel')], max_length=50),
        ),
    ]
