# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0037_auto_20160812_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
