# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0038_delete_itemtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='special_procedure',
        ),
        migrations.AddField(
            model_name='procedure',
            name='gender',
            field=models.CharField(choices=[('sterilisation', 'Sterilisation'), ('euthanasia', 'Euthanasia')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
