# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0039_auto_20160813_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='gender',
            new_name='special_procedure',
        ),
    ]
