# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0040_auto_20160813_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoryanalysispanel',
            options={'verbose_name_plural': 'laboratory panels'},
        ),
    ]
