# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentstatus',
            options={'verbose_name_plural': 'appointment status'},
        ),
    ]
