# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20160808_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='consultation',
        ),
    ]
