# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='uuid',
        ),
    ]
