# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_remove_appointment_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='createdby',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='modifiedby',
            new_name='modified_by',
        ),
    ]
