# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_auto_20160810_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_by',
        ),
    ]
