# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_appointment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('arrived', 'arrived'), ('in consult', 'in consult'), ('waiting to pay', 'waiting to pay'), ('payment complete', 'payment complete')], max_length=50),
        ),
    ]
