# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_auto_20160812_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('arrived', 'Arrived'), ('in consult', 'In Consult'), ('waiting to pay', 'Waiting to Pay'), ('payment complete', 'Payment Complete')], max_length=50),
        ),
    ]
