# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_auto_20160812_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentStatus',
        ),
    ]
