# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_delete_appointmentstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patients',
        ),
    ]
