# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_auto_20160813_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end',
        ),
    ]
