# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_remove_appointment_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='practice',
        ),
    ]
