# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 12:02
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_auto_20160820_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patients',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='client', chained_model_field='client', to='visitors.Patient'),
        ),
    ]
