# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0027_auto_20160820_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='attending_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
