# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0029_appointment_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_con', to='consultations.Consultation'),
        ),
    ]
