# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_tag2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tag1',
        ),
        migrations.DeleteModel(
            name='Tag2',
        ),
    ]
