# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_auto_20160810_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
