# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('test1', '0006_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='content_type1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='object_id1',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='contenttypes.ContentType'),
        ),
    ]
