# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0007_auto_20160810_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='name',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
