# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('test1', '0008_auto_20160810_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='related object')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content page')),
            ],
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type1',
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
