# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('test1', '0010_auto_20160810_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='object_id',
            new_name='caller_id',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='relation_id',
            new_name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='caller_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caller_type', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='receiver_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_type', to='contenttypes.ContentType'),
        ),
    ]
