# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0011_auto_20160810_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='caller_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xcaller_type', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='receiver_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xreceiver_type', to='contenttypes.ContentType'),
        ),
    ]
