# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0012_auto_20160811_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='caller_type',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='receiver_type',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
