# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('streetaddress', models.CharField(blank=True, max_length=100)),
                ('streetaddress2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('organisationname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('species', models.CharField(blank=True, max_length=20)),
                ('breed', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=30)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('microchip', models.CharField(blank=True, max_length=30)),
                ('archived', models.BooleanField(default=False)),
                ('deceased', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
