# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20160808_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='organisationname',
            new_name='organisation_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='streetaddress',
            new_name='street_address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='streetaddress2',
            new_name='street_address_2',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
    ]
