# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_auto_20160811_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_fk', to='visitors.Species'),
        ),
    ]
