# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_auto_20160812_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.Species'),
        ),
    ]
