# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_auto_20160812_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('female sterilised', 'Female Sterilised'), ('male', 'Male'), ('male sterilised', 'Male Sterilised'), ('unknown', 'Unknown')], max_length=50),
        ),
    ]
