# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0012_auto_20160813_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientGender',
        ),
    ]
