# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0013_delete_patientgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='species_code',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
