# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0014_species_species_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
