# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0020_auto_20160820_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='visitors.Client'),
        ),
    ]
