# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0023_auto_20160823_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Weight (kg)'),
        ),
    ]
