# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nutrition', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('type', models.IntegerField()),
                ('type_name', models.CharField(max_length=40)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price_vat_rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketLaboratoryAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sample', models.CharField(max_length=50)),
                ('basket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketlaboratoryanalysis_basket_fk', to='basket.BasketItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active_substance', models.CharField(blank=True, max_length=100)),
                ('package_type', models.CharField(max_length=50, unique=True)),
                ('dispensing_unit', models.CharField(max_length=50, unique=True)),
                ('total_dispensing_units_in_package', models.IntegerField(default=0)),
                ('controlled_substance', models.BooleanField(default=False)),
                ('vaccine', models.BooleanField(default=False)),
                ('instructions', models.CharField(blank=True, max_length=500)),
                ('basket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketmedicine_basketitem_fk', to='basket.BasketItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('duration', models.IntegerField()),
                ('basket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketprocedure_basket_fk', to='basket.BasketItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('basket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketsupply_basketitem_fk', to='basket.BasketItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='basketfood',
            name='basket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketfood_basket_fk', to='basket.BasketItem'),
        ),
        migrations.AddField(
            model_name='basket',
            name='BasketItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_basket_id_fk', to='basket.BasketItem'),
        ),
        migrations.AddField(
            model_name='basket',
            name='CallID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.Call'),
        ),
    ]
