# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketsupply',
            options={'verbose_name_plural': 'basket supplies'},
        ),
    ]
