# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20160811_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='CallID',
        ),
    ]
