# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_auto_20160811_2058'),
        ('basket', '0003_remove_basket_callid'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='CallID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calls.Call'),
            preserve_default=False,
        ),
    ]
