# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_basket_callid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='CallID',
        ),
    ]
