# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_remove_basket_callid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='BasketItemID',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='basket.Basket'),
            preserve_default=False,
        ),
    ]
