# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20160813_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sample', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sample', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='basketlaboratoryanalysis',
            name='basket_item',
        ),
        migrations.AlterField(
            model_name='basketfood',
            name='basket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_foods', to='basket.BasketItem'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='basket.Basket'),
        ),
        migrations.AlterField(
            model_name='basketmedicine',
            name='basket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_medicines', to='basket.BasketItem'),
        ),
        migrations.AlterField(
            model_name='basketprocedure',
            name='basket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_procedures', to='basket.BasketItem'),
        ),
        migrations.AlterField(
            model_name='basketsupply',
            name='basket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_supplies', to='basket.BasketItem'),
        ),
        migrations.DeleteModel(
            name='BasketLaboratoryAnalysis',
        ),
        migrations.AddField(
            model_name='basketpanel',
            name='basket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_panels', to='basket.BasketItem'),
        ),
        migrations.AddField(
            model_name='basketanalysis',
            name='basket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_analyses', to='basket.BasketItem'),
        ),
    ]
