# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20160813_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('counter sale', 'Counter Sale'), ('estimate', 'Estimate'), ('repeat prescription', 'Repeat Prescription'), ('web sale', 'Web Sale')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
