# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('analysis', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PanelReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('panel', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
