# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_auto_20160813_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanelReference',
            new_name='PanelTestRange',
        ),
    ]
