# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_auto_20160813_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paneltestrange',
            name='panel',
        ),
        migrations.AddField(
            model_name='paneltestrange',
            name='name',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='labs.PanelTest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paneltest',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
