# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_auto_20160813_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paneltestrange',
            old_name='name',
            new_name='ggg',
        ),
    ]
