# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_auto_20160812_2233'),
        ('labs', '0008_auto_20160813_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreference',
            name='species',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='visitors.Species'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paneltestrange',
            name='species',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='visitors.Species'),
            preserve_default=False,
        ),
    ]
